Add Readme manually as GitBash is not cooperating
Because I have tried for over an hour, to create and sync this repository from my local machine and here via GitBash and continue getting errors like:
error: failed to push some refs to 'https://github.com/autumn-info-442a/team-f/tree/main/homework-3'
or
fatal: remote origin already exists.
or
fatal: repository 'https://github.com/autumn-info-442a/team-f/tree/main/homework-3/' not found

So I don't know how to upload it anyway but manually.